 linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - nolintlint
    - staticcheck
    - typecheck
    - unconvert
    - gocritic
    - unused
    - misspell
    - stylecheck
    - whitespace
