generator:
  namespace: observatorium-logs-test
  image: quay.io/openshift-logging/cluster-logging-load-client:latest
  tenant: observatorium
  pushURL: http://observatorium-loki-distributor-http.observatorium-logs-test.svc.cluster.local:3100/loki/api/v1/push
