scenarios:
  highVolumeReads:
    enabled: false
    description: "Query range 2 weeks"
    startThreshold: 1000000000
    readers: 
      replicas: 5
      queries:
        sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
        sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
      queryRange: "336h"
