scenarios:
  queryPath:
    enabled: false
    description: "Query range 1 week"
    readers: 
      replicas: 5
      queries:
        sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
        sumRateErrorsOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
      queryRange: "168h"
