scenarios:
  highVolumeReads:
    enabled: true
    description: "Query range 1 second"
    readers: 
      replicas: 5
      queries:
        sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
        sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
      queryRange: "1s"
