scenarios:
  highVolumeWrites:
    enabled: true
    description: "Write 1 TB per day"
    writers:
      replicas: 12
      args:
        log-type: synthetic
        label-type: client-host
        logs-per-second: 1000
        synthetic-payload-size: 1000
