scenarios:
  highVolumeWrites:
    enabled: true
    description: "Write 500 GB per day"
    writers:
      replicas: 6
      args:
        source: synthetic
        loki-labels: host
        log-lines-rate: 1000
        synthetic-payload-size: 1000
