scenarios:
  highVolumeWrites:
    enabled: true
    description: "Write 2 TB per day"
    samples:
      total: 10
      interval: "1m" 
    writers:
      replicas: 24
      args:
        source: synthetic
        loki-labels: host
        log-lines-rate: 1000
        synthetic-payload-size: 1000
