scenarios:
  ingestionPath:
    enabled: true
    description: "Write 8 TB per day"
    writers:
      replicas: 96
      args:
        log-type: synthetic
        label-type: client-host
        logs-per-second: 1000
        synthetic-payload-size: 1000
