scenarios:
  highVolumeWrites:
    enabled: false
    description: "Write 16 TB per day"
    writers:
      replicas: 192
      args:
        log-type: synthetic
        label-type: client-host
        logs-per-second: 1000
        synthetic-payload-size: 1000
