scenarios:
  highVolumeReads:
    enabled: false
    generator:
      replicas: 10
      args:
        source: application
        log-lines-rate: 500
    startThreshold: 1000000000
    samples:
      total: 10
      interval: "1m"
    configurations:
      - description: "Query range 1 second"
        readers: 
          replicas: 5
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            query-range: "1s"
      - description: "Query range 1 minute"
        readers:
          replicas: 5
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            query-range: "1m"
      - description: "Query range 1 hour"
        readers:
          replicas: 5
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            query-range: "1h"
      - description: "Query range 1 day"
        readers:
          replicas: 5
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            query-range: "24h"
      - description: "Query range 1 week"
        readers:
          replicas: 5
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            query-range: "168h"
      - description: "Query range 2 weeks"
        readers:
          replicas: 5
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            query-range: "336h"
      - description: "Query range 1 month"
        readers:
          replicas: 5
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            query-range: "744h"
  highVolumeWrites:
    enabled: true
    samples:
      total: 10
      interval: "1m"
    configurations:
      - description: "Write 250 GB per day"
        writers:
          replicas: 3
          args:
            source: synthetic
            loki-labels: host
            log-lines-rate: 1000
            synthetic-payload-size: 1000
      - description: "Write 500 GB per day"
        writers:
          replicas: 6
          args:
            source: synthetic
            loki-labels: host
            log-lines-rate: 1000
            synthetic-payload-size: 1000
      - description: "Write 1 TB per day"
        writers:
          replicas: 12
          args:
            source: synthetic
            loki-labels: host
            log-lines-rate: 1000
            synthetic-payload-size: 1000
      - description: "Write 2 TB per day"
        writers:
          replicas: 24
          args:
            source: synthetic
            loki-labels: host
            log-lines-rate: 1000
            synthetic-payload-size: 1000
      - description: "Write 4 TB per day"
        writers:
          replicas: 48
          args:
            source: synthetic
            loki-labels: host
            log-lines-rate: 1000
            synthetic-payload-size: 1000
      - description: "Write 8 TB per day"
        writers:
          replicas: 96
          args:
            source: synthetic
            loki-labels: host
            log-lines-rate: 1000
            synthetic-payload-size: 1000
      - description: "Write 16 TB per day"
        writers:
          replicas: 96
          args:
            source: synthetic
            loki-labels: host
            log-lines-rate: 1000
            synthetic-payload-size: 2000
      - description: "Write 32 TB per day"
        writers:
          replicas: 192
          args:
            source: synthetic
            loki-labels: host
            log-lines-rate: 1000
            synthetic-payload-size: 2000
