scenarios:
  highVolumeReads:
    enabled: false
    generator:
      replicas: 10
      args:
        source: application
        destination: loki
        log-lines-rate: 1000
    startThreshold: 500000000
    samples:
      interval: "60s"
      range: "1m"
      total: 10
    configurations:
      - description: "Query range 1 second"
        readers: 
          replicas: 1
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "1s"
      - description: "Query range 1 minute"
        readers:
          replicas: 1
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "1m"
      - description: "Query range 1 hour"
        readers:
          replicas: 1
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "1h"
      - description: "Query range 1 day"
        readers:
          replicas: 1
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "24h"
      - description: "Query range 1 week"
        readers:
          replicas: 1
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "168h"
      - description: "Query range 2 weeks"
        readers:
          replicas: 1
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "336h"
      - description: "Query range 1 month"
        readers:
          replicas: 1
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "744h"
  highVolumeWrites:
    enabled: true
    samples:
      interval: "60s"
      range: "1m"
      total: 10
    configurations:
      - description: "Write 250 GB per day"
        writers:
          replicas: 50
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 58
            synthetic-payload-size: 1000
      - description: "Write 500 GB per day"
        writers:
          replicas: 50
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 116
            synthetic-payload-size: 1000
      - description: "Write 1 TB per day"
        writers:
          replicas: 50
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 240
            synthetic-payload-size: 1000
      - description: "Write 2 TB per day"
        writers:
          replicas: 50
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 480
            synthetic-payload-size: 1000
      - description: "Write 4 TB per day"
        writers:
          replicas: 50
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 940
            synthetic-payload-size: 1000
      - description: "Write 8 TB per day"
        writers:
          replicas: 50
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 1860
            synthetic-payload-size: 1000
      - description: "Write 16 TB per day"
        writers:
          replicas: 50
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 3800
            synthetic-payload-size: 1000
      - description: "Write 32 TB per day"
        writers:
          replicas: 50
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 7600
            synthetic-payload-size: 1000
