scenarios:
  highVolumeWrites:
    enabled: true
    samples:
      interval: "60s"
      range: "60s"
      total: 2
    configurations:
      - description: "Write 500 MB per day"
        writers:
          replicas: 1
          args:
            source: synthetic
            destination: loki
            log-lines-rate: 60
            synthetic-payload-size: 150
  highVolumeReads:
    enabled: true
    generator:
      replicas: 1
      args:
        source: application
        destination: loki
        log-lines-rate: 200
    startThreshold: 5000
    samples:
      interval: "60s"
      range: "60s"
      total: 2
    configurations:
      - description: "Query range 1 second"
        readers:
          replicas: 1
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "1s"
