scenarios:
  highVolumeWrites:
    enabled: true
    samples:
      interval: "60s"
      range: "60s"
      total: 2
    configurations:
      - description: "Write 100 logs-per-second"
        writers:
          replicas: 1
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 100
            synthetic-payload-size: 100
  highVolumeReads:
    enabled: true
    generator:
      replicas: 10
      args:
        source: application
        destination: loki
        log-lines-rate: 1000
    startThreshold: 25000000
    samples:
      interval: "60s"
      range: "60s"
      total: 2
    configurations:
      - description: "Read 10 queries-per-second"
        readers:
          replicas: 1
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
