---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-benchmarks-querier-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-benchmarks-generator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-benchmarks-querier-clusterrole
rules:
- apiGroups:
  - loki.grafana.com
  resources:
  - application
  resourceNames:
  - logs
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-benchmarks-generator-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - loki.grafana.com
  resources:
  - application
  resourceNames:
  - logs
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-benchmarks-querier-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-benchmarks-querier-clusterrole
subjects:
- kind: ServiceAccount
  name: loki-benchmarks-querier-sa
  namespace: openshift-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-benchmarks-generator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-benchmarks-generator-clusterrole
subjects:
- kind: ServiceAccount
  name: loki-benchmarks-generator-sa
  namespace: openshift-logging

