logger:
  name: logger
  namespace: default
  image: quay.io/openshift-logging/cluster-logging-load-client:latest
  tenantId: observatorium

querier:
  name: querier
  namespace: default
  image: docker.io/grafana/logcli:2.6.1-amd64
  tenantId: observatorium

metrics:
  url: http://127.0.0.1:9090
  enableCadvisorMetrics: false
  # Align these with ./prometheus/config.yaml
  jobs:
    distributor: loki-distributor
    ingester: loki-ingester
    querier: loki-querier
    queryFrontend: loki-query-frontend

loki:
  distributor: http://observatorium-xyz-loki-distributor-http.observatorium.svc.cluster.local:3100
  queryFrontend: http://observatorium-xyz-loki-query-frontend-http.observatorium.svc.cluster.local:3100

scenarios:
  highVolumeWrites:
    enabled: true
    samples:
      interval: "60s"
      range: "60s"
      total: 2
    configurations:
      - description: "Write 100 logs-per-second"
        writers:
          replicas: 1
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 100
            synthetic-payload-size: 100
  highVolumeReads:
    enabled: true
    generator:
      replicas: 10
      args:
        source: application
        destination: loki
        log-lines-rate: 1000
    startThreshold: 25000000
    samples:
      interval: "60s"
      range: "60s"
      total: 2
    configurations:
      - description: "Read 10 queries-per-second"
        readers:
          replicas: 1
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
