logger:
  name: logger
  namespace: default
  image: quay.io/openshift-logging/cluster-logging-load-client:latest
  tenantId: observatorium

querier:
  name: querier
  namespace: default
  image: quay.io/openshift-logging/cluster-logging-load-client:latest
  tenantId: observatorium

metrics:
  url: http://127.0.0.1:9090
  enableCadvisorMetrics: false
  # Align these with ./prometheus/config.yaml
  jobs:
    distributor:
        job: loki-distributor
        queryLabel: job
    ingester:
        job: loki-ingester
        queryLabel: job
    querier:
        job: loki-querier
        queryLabel: job
    queryFrontend:
        job: loki-query-frontend
        queryLabel: job

loki:
  distributor: http://observatorium-xyz-loki-distributor-http.observatorium.svc.cluster.local:3100
  queryFrontend: http://observatorium-xyz-loki-query-frontend-http.observatorium.svc.cluster.local:3100

scenarios:
  highVolumeWrites:
    enabled: true
    configurations:
      - description: "Write 100 logs-per-second"
        samples:
          interval: "60s"
          range: "60s"
          total: 2
        writers:
          replicas: 1
          command: generate
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 100
            synthetic-payload-size: 100
  highVolumeReads:
    enabled: true
    configurations:
      - description: "Read 10 queries-per-second"
        samples:
          interval: "60s"
          range: "60s"
          total: 2
        writers:
          replicas: 10
          command: generate
          args:
            source: application
            destination: loki
            log-lines-rate: 1000
        readers:
          startThreshold: 25000000
          replicas: 1
          command: query
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
