LOKI_COMPACTOR_CPU_REQUESTS=2000m
LOKI_COMPACTOR_CPU_LIMITS=4000m
LOKI_COMPACTOR_MEMORY_REQUESTS=4Gi
LOKI_COMPACTOR_MEMORY_LIMITS=8Gi
LOKI_DISTRIBUTOR_REPLICAS="2"
LOKI_DISTRIBUTOR_CPU_REQUESTS=2000m
LOKI_DISTRIBUTOR_CPU_LIMITS=4000m
LOKI_DISTRIBUTOR_MEMORY_REQUESTS=2Gi
LOKI_DISTRIBUTOR_MEMORY_LIMITS=4Gi
LOKI_INGESTER_REPLICAS="3"
LOKI_INGESTER_CPU_REQUESTS=6000m
LOKI_INGESTER_CPU_LIMITS=12000m
LOKI_INGESTER_MEMORY_REQUESTS=30Gi
LOKI_INGESTER_MEMORY_LIMITS=60Gi
LOKI_QUERIER_REPLICAS="3"
LOKI_QUERIER_CPU_REQUESTS=6000m
LOKI_QUERIER_CPU_LIMITS=12000m
LOKI_QUERIER_MEMORY_REQUESTS=10Gi
LOKI_QUERIER_MEMORY_LIMITS=20Gi
LOKI_QUERY_FRONTEND_REPLICAS="2"
LOKI_QUERY_FRONTEND_CPU_REQUESTS=4000m
LOKI_QUERY_FRONTEND_CPU_LIMITS=8000m
LOKI_QUERY_FRONTEND_MEMORY_REQUESTS=2.5Gi
LOKI_QUERY_FRONTEND_MEMORY_LIMITS=5Gi
LOKI_REPLICATION_FACTOR="3"
LOKI_QUERY_PARALLELISM="2"
LOKI_CHUNK_CACHE_REPLICAS="2"
LOKI_CHUNK_CACHE_CPU_REQUESTS=500m
LOKI_CHUNK_CACHE_CPU_LIMITS="3"
LOKI_CHUNK_CACHE_MEMORY_REQUESTS=5016Mi
LOKI_CHUNK_CACHE_MEMORY_LIMITS=6Gi
LOKI_INDEX_QUERY_CACHE_REPLICAS="2"
LOKI_INDEX_QUERY_CACHE_CPU_REQUESTS=500m
LOKI_INDEX_QUERY_CACHE_CPU_LIMITS="3"
LOKI_INDEX_QUERY_CACHE_MEMORY_REQUESTS=1329Mi
LOKI_INDEX_QUERY_CACHE_MEMORY_LIMITS=1536Mi
LOKI_RESULTS_CACHE_REPLICAS="2"
LOKI_RESULTS_CACHE_CPU_REQUESTS=500m
LOKI_RESULTS_CACHE_CPU_LIMITS="3"
LOKI_RESULTS_CACHE_MEMORY_REQUESTS=1329Mi
LOKI_RESULTS_CACHE_MEMORY_LIMITS=1536Mi
LOKI_PVC_REQUEST=10Gi
MEMCACHED_CPU_REQUEST=500m
MEMCACHED_CPU_LIMIT="3"
MEMCACHED_MEMORY_REQUEST=1329Mi
MEMCACHED_MEMORY_LIMIT=1844Mi
MEMCACHED_EXPORTER_CPU_REQUEST=50m
MEMCACHED_EXPORTER_CPU_LIMIT=200m
MEMCACHED_EXPORTER_MEMORY_REQUEST=50Mi
MEMCACHED_EXPORTER_MEMORY_LIMIT=200Mi
