logger:
  name: logger
  namespace:  observatorium-logs-test
  image: quay.io/periklis/logger:latest
  tenantId: observatorium

querier:
  name: querier
  namespace: observatorium-logs-test
  image: quay.io/periklis/hey:latest
  tenantId: observatorium

metrics:
  url: http://127.0.0.1:9090
  enableCadvisorMetrics: true
  # Align these with ./prometheus/config.yaml
  jobs:
    distributor: loki-distributor
    ingester: loki-ingester
    querier: loki-querier
    queryFrontend: loki-query-frontend
  # cadvisor job names
  cadvisorJobs:
    ingester: cadvisor_ingesters

loki:
  distributor: http://observatorium-loki-distributor-http.observatorium-logs-test.svc.cluster.local:3100
  queryFrontend: http://observatorium-loki-query-frontend-http.observatorium-logs-test.svc.cluster.local:3100

scenarios:
  highVolumeReads:
    enabled: true
    configurations:
      - description: "Read 20 queries-per-second"
        samples:
          interval: "15s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
          throughput: 100
          messageSize: 100
        readers:
          replicas: 1
          throughput: 10
          queries:
            sumRateByLevel: 'sum(rate({component!=""}[5m])) by (level)'
          startThreshold: 1024000
      - description: "Read 20*3 queries-per-second"
        samples:
          interval: "15s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
          throughput: 100
          messageSize: 100
        readers:
          replicas: 1
          throughput: 10
          queries:
            topTenComponents: 'topk(10, sum(rate({component!=""}[5m])) by (level))'
            countOverTime: 'count_over_time({component!=""}[5m])'
            bytesOverTime: 'bytes_over_time({component!=""}[5m])'
          startThreshold: 1024000
      - description: "Read 20*8 queries-per-second"
        samples:
          interval: "15s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
          throughput: 100
          messageSize: 100
        readers:
          replicas: 1
          throughput: 10
          queries:
            sumRateByLevel: 'sum(rate({component!=""}[1m])) by (level)'
            devopsend: 'sum(rate({component="devopsend"}[1m])) by (level)'
            fullstackend: 'sum(rate({component="fullstackend"}[1m])) by (level)'
            frontend: 'sum(rate({component="frontend"}[1m])) by (level)'
            backend: 'sum(rate({component="backend"}[1m])) by (level)'
            allpanics: 'sum(rate({msg=~"panic.*"}[1m]))'
            countpanics: 'count_over_time({msg=~"panic.*"}[5m])'
            topTenErrors: 'topk(10, sum(rate({component!="", level="error"}[5m])) by (component))'
          startThreshold: 1024000
  highVolumeWrites:
    enabled: true
    configurations:
      - description: "Write 1,000 logs-per-second"
        samples:
          interval: "20s"
          range: "30s"
          total: 18
        writers:
          replicas: 1
          throughput: 1000
          messageSize: 100
      - description: "Write 5,000 logs-per-second"
        samples:
          interval: "20s"
          range: "30s"
          total: 18
        writers:
          replicas: 5
          throughput: 1000
          messageSize: 100
      - description: "Write 10,000 logs-per-second"
        samples:
          interval: "20s"
          range: "30s"
          total: 18
        writers:
          replicas: 10
          throughput: 1000
          messageSize: 100
      - description: "Write 20,000 logs-per-second"
        samples:
          interval: "20s"
          range: "30s"
          total: 18
        writers:
          replicas: 10
          throughput: 2000
          messageSize: 100
      - description: "Write 50,000 logs-per-second"
        samples:
          interval: "20s"
          range: "30s"
          total: 6
        writers:
          replicas: 10
          throughput: 5000
          messageSize: 100
