logger:
  name: logger
  namespace:  loki
  image: quay.io/periklis/logger:latest
  tenantId: benchmark

querier:
  name: querier
  namespace: loki
  image: quay.io/periklis/hey:latest
  tenantId: benchmark

metrics:
  url: http://127.0.0.1:9090
  # Align these with ./prometheus/config.yaml
  jobs:
    distributor: loki-distributor
    ingester: loki-ingester
    querier: loki-querier
    queryFrontend: loki-query-frontend

loki:
  distributor: http://loki-loki-distributed-distributor.loki.svc.cluster.local:3100
  queryFrontend: http://loki-loki-distributed-query-frontend.loki.svc.cluster.local:3100

scenarios:
  highVolumeWrites:
    enabled: true
    samples:
      interval: "10s"
      range: "1m"
      total: 30
    writers:
      replicas: 3
      throughput: 2000
