logger:
  name: logger
  namespace:  observatorium-logs-test
  image: quay.io/openshift-logging/cluster-logging-load-client:latest
  tenantId: observatorium

querier:
  name: querier
  namespace: observatorium-logs-test
  image: quay.io/openshift-logging/cluster-logging-load-client:latest
  tenantId: observatorium

metrics:
  url: http://127.0.0.1:9090
  enableCadvisorMetrics: true
  # Align these with ./prometheus/config.yaml
  jobs:
    distributor:
        job: loki-distributor
        queryLabel: job
    ingester:
        job: loki-ingester
        queryLabel: job
    querier:
        job: loki-querier
        queryLabel: job
    queryFrontend:
        job: loki-query-frontend
        queryLabel: job
  cadvisorJobs:
    ingester:
        job: loki-ingester
        queryLabel: pod
    querier:
        job: loki-querier
        queryLabel: pod

loki:
  distributor: http://observatorium-loki-distributor-http.observatorium-logs-test.svc.cluster.local:3100
  queryFrontend: http://observatorium-loki-query-frontend-http.observatorium-logs-test.svc.cluster.local:3100

scenarios:
  highVolumeReads:
    enabled: true
    configurations:
      - description: "Query range 1 second"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
          command: generate
          args:
            source: application
            destination: loki
            log-lines-rate: 1000
        readers:
          startThreshold: 500000000
          replicas: 1
          command: query
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "1s"
      - description: "Query range 1 minute"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
          command: generate
          args:
            source: application
            destination: loki
            log-lines-rate: 1000
        readers:
          startThreshold: 500000000
          replicas: 1
          command: query
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "1m"
      - description: "Query range 1 hour"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
          command: generate
          args:
            source: application
            destination: loki
            log-lines-rate: 1000
        readers:
          startThreshold: 500000000
          replicas: 1
          command: query
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "1h"
      - description: "Query range 1 day"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
          command: generate
          args:
            source: application
            destination: loki
            log-lines-rate: 1000
        readers:
          startThreshold: 500000000
          replicas: 1
          command: query
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "24h"
      - description: "Query range 1 week"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
          command: generate
          args:
            source: application
            destination: loki
            log-lines-rate: 1000
        readers:
          startThreshold: 500000000
          replicas: 1
          command: query
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "168h"
      - description: "Query range 2 weeks"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
          command: generate
          args:
            source: application
            destination: loki
            log-lines-rate: 1000
        readers:
          startThreshold: 500000000
          replicas: 1
          command: query
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "336h"
      - description: "Query range 1 month"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
          command: generate
          args:
            source: application
            destination: loki
            log-lines-rate: 1000
        readers:
          startThreshold: 500000000
          replicas: 1
          command: query
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "744h"
  highVolumeWrites:
    enabled: true
    configurations:
      - description: "Write 250 GB per day"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 50
          command: generate
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 58
            synthetic-payload-size: 1000
      - description: "Write 500 GB per day"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 50
          command: generate
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 116
            synthetic-payload-size: 1000
      - description: "Write 1 TB per day"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 50
          command: generate
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 240
            synthetic-payload-size: 1000
      - description: "Write 2 TB per day"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 50
          command: generate
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 480
            synthetic-payload-size: 1000
      - description: "Write 4 TB per day"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 50
          command: generate
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 940
            synthetic-payload-size: 1000
      - description: "Write 8 TB per day"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 50
          command: generate
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 1860
            synthetic-payload-size: 1000
      - description: "Write 16 TB per day"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 50
          command: generate
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 3800
            synthetic-payload-size: 1000
      - description: "Write 32 TB per day"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 50
          command: generate
          args:
            source: synthetic
            destination: loki
            loki-labels: host
            log-lines-rate: 7600
            synthetic-payload-size: 1000
