logger:
  name: logger
  namespace:  observatorium-logs-test
  image: quay.io/openshift-logging/cluster-logging-load-client:latest
  tenantId: observatorium

querier:
  name: querier
  namespace: observatorium-logs-test
  image: quay.io/openshift-logging/cluster-logging-load-client:latest
  tenantId: observatorium

metrics:
  url: http://127.0.0.1:9090
  enableCadvisorMetrics: true
  # Align these with ./prometheus/config.yaml
  jobs:
    distributor:
        job: loki-distributor
        queryLabel: job
    ingester:
        job: loki-ingester
        queryLabel: job
    querier:
        job: loki-querier
        queryLabel: job
    queryFrontend:
        job: loki-query-frontend
        queryLabel: job
  cadvisorJobs:
    ingester:
        job: loki-ingester
        queryLabel: pod
    querier:
        job: loki-querier
        queryLabel: pod

loki:
  distributor: http://observatorium-loki-distributor-http.observatorium-logs-test.svc.cluster.local:3100
  queryFrontend: http://observatorium-loki-query-frontend-http.observatorium-logs-test.svc.cluster.local:3100

scenarios:
  highVolumeReads:
    enabled: true
    configurations:
      - description: "Query range 1 hour"
        samples:
          interval: "60s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
          command: generate
          args:
            source: application
            destination: loki
            log-lines-rate: 250
        readers:
          startThreshold: 500000000
          replicas: 1
          command: query
          queries:
            sumRateByLevel: 'sum by (level) (rate({client="promtail"} [1s]))'
            sumRateErrosOnly: 'sum(rate({client="promtail"} |= "level=error" [1s]))'
          args:
            destination: loki
            log-lines-rate: 10
            query-duration: "481h"
