logger:
  name: logger
  namespace:  observatorium-logs-test
  image: quay.io/periklis/logger:latest
  tenantId: observatorium

querier:
  name: querier
  namespace: observatorium-logs-test
  image: quay.io/periklis/hey:latest
  tenantId: observatorium

metrics:
  url: http://127.0.0.1:9090
  enableCadvisorMetrics: true
  # Align these with ./prometheus/config.yaml
  jobs:
    distributor: loki-distributor
    ingester: loki-ingester
    querier: loki-querier
    queryFrontend: loki-query-frontend
  # cadvisor job names
  cadvisorJobs:
    ingester: cadvisor_ingesters

loki:
  distributor: http://observatorium-loki-distributor-http.observatorium-logs-test.svc.cluster.local:3100
  queryFrontend: http://observatorium-loki-query-frontend-http.observatorium-logs-test.svc.cluster.local:3100

scenarios:
  highVolumeReads:
    enabled: true
    configurations:
      - description: "Query range 1 second"
        samples:
          interval: "15s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
        readers:
          replicas: 1
          throughput: 10
          queries:
            sumRateByLevel: 'sum(rate({component!=""}[1s])) by (level)'
            sumRateErrosOnly: 'sum(rate({component!="", level="error"}[1s]))'
          startThreshold: 1000000
      - description: "Query range 1 minute"
        samples:
          interval: "15s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
        readers:
          replicas: 1
          throughput: 10
          queries:
            sumRateByLevel: 'sum(rate({component!=""}[1m])) by (level)'
            sumRateErrosOnly: 'sum(rate({component!="", level="error"}[1m]))'
          startThreshold: 1500000
      - description: "Query range 1 hour"
        samples:
          interval: "15s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
        readers:
          replicas: 1
          throughput: 10
          queries:
            sumRateByLevel: 'sum(rate({component!=""}[1h])) by (level)'
            sumRateErrosOnly: 'sum(rate({component!="", level="error"}[1h]))'
          startThreshold: 3000000
      - description: "Query range 1 day"
        samples:
          interval: "15s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
        readers:
          replicas: 1
          throughput: 10
          queries:
            sumRateByLevel: 'sum(rate({component!=""}[1d])) by (level)'
            sumRateErrosOnly: 'sum(rate({component!="", level="error"}[1d]))'
          startThreshold: 5000000
      - description: "Query range 1 week"
        samples:
          interval: "15s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
        readers:
          replicas: 1
          throughput: 10
          queries:
            sumRateByLevel: 'sum(rate({component!=""}[1w])) by (level)'
            sumRateErrosOnly: 'sum(rate({component!="", level="error"}[1w]))'
          startThreshold: 10000000
      - description: "Query range 2 weeks"
        samples:
          interval: "15s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
        readers:
          replicas: 1
          throughput: 10
          queries:
            sumRateByLevel: 'sum(rate({component!=""}[2w])) by (level)'
            sumRateErrosOnly: 'sum(rate({component!="", level="error"}[2w]))'
          startThreshold: 20000000
      - description: "Query range 1 month"
        samples:
          interval: "15s"
          range: "1m"
          total: 10
        writers:
          replicas: 10
        readers:
          replicas: 1
          throughput: 10
          queries:
            sumRateByLevel: 'sum(rate({component!=""}[31d])) by (level)'
            sumRateErrosOnly: 'sum(rate({component!="", level="error"}[31d]))'
          startThreshold: 50000000
  highVolumeWrites:
    enabled: true
    configurations:
      - description: "Write 250 GB per day"
        samples:
          interval: "20s"
          range: "30s"
          total: 15
        writers:
          replicas: 10
          args:
            logps: 1000
            message-size: 300
      - description: "Write 500 GB per day"
        samples:
          interval: "20s"
          range: "30s"
          total: 15
        writers:
          replicas: 10
          args:
            logps: 1000
            message-size: 600
      - description: "Write 1 TB per day"
        samples:
          interval: "20s"
          range: "30s"
          total: 15
        writers:
          replicas: 20
          args:
            logps: 1000
            message-size: 500
      - description: "Write 2 TB per day"
        samples:
          interval: "20s"
          range: "30s"
          total: 15
        writers:
          replicas: 20
          args:
            logps:: 2000
            message-size: 500
      - description: "Write 4 TB per day"
        samples:
          interval: "20s"
          range: "30s"
          total: 15
        writers:
          replicas: 20
          args:
            logps: 5000
            message-size: 500
      - description: "Write 8 TB per day"
        samples:
          interval: "20s"
          range: "30s"
          total: 15
        writers:
          replicas: 20
          args:
            logps: 5000
            message-size: 900
      - description: "Write 16 TB per day"
        samples:
          interval: "20s"
          range: "30s"
          total: 15
        writers:
          replicas: 25
          args:
            logps: 10000
            message-size: 800
      - description: "Write 32 TB per day"
        samples:
          interval: "20s"
          range: "30s"
          total: 15
        writers:
          replicas: 40
          args:
            logps: 10000
            message-size: 1000
