metrics:
  url: http://127.0.0.1:9090
  enableCadvisorMetrics: true
  jobs:
    distributor: loki-distributor
    ingester: loki-ingester
    querier: loki-querier
    queryFrontend: loki-query-frontend
